// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const cleanEnvVar = (val?: string) => {
  if (!val) return val;
  return val.replace(/^["']|["']$/g, ''); // Remove leading and trailing double/single quotes
};

function createSupabaseClient() {
  const rawUrl = import.meta.env.VITE_SUPABASE_URL || (typeof process !== "undefined" ? process.env?.SUPABASE_URL : undefined);
  const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (typeof process !== "undefined" ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);
  
  const cleanUrl = cleanEnvVar(rawUrl);
  const cleanKey = cleanEnvVar(rawKey);

  const SUPABASE_URL = (cleanUrl && cleanUrl !== "undefined" && cleanUrl !== "null") ? cleanUrl : "https://nqbpykmvvjrytnwljkir.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY = (cleanKey && cleanKey !== "undefined" && cleanKey !== "null") ? cleanKey : "sb_publishable_ZftPqa-FN2fEFn6RofNDYg_cK46QKO7";

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Please configure them in your environment variables.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const options: any = {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  };

  // Provide a dummy WebSocket class for the serverless SSR environment
  // to prevent Node 20 native WebSocket check errors
  if (typeof window === 'undefined') {
    options.realtime = {
      transport: class DummyWebSocket {}
    };
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, options);
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
